export { default as Header } from "./Header";
export { default as Home } from "./Home";
export { default as Cadastro } from "./Cadastro";
export { default as Dados } from "./Dados";
export { default as Validacao } from "./Validacao";
export { default as Remocao } from "./Remocao";
export { default as Consulta } from "./Consulta";
export { default as Portaria } from "./Portaria";
export { default as Configuracao } from "./Configuracao";